/* Generated by Yosys 0.9+932 (git sha1 22fe931, gcc 4.8.4-2ubuntu1~14.04.4 -fPIC -Os) */

(* top =  1  *)
(* src = "tests/simple/fiedler-cooley.v:3" *)
module up3down5(clock, data_in, up, down, carry_out, borrow_out, count_out, parity_out);
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  wire _000_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  wire _001_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  wire [9:0] _002_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  wire [9:0] _003_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  wire [8:0] _004_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  wire _005_;
  wire [1:0] _006_;
  wire [1:0] _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire [1:0] _013_;
  wire [1:0] _014_;
  wire [1:0] _015_;
  wire [3:0] _016_;
  wire [1:0] _017_;
  wire _018_;
  wire _019_;
  wire [1:0] _020_;
  wire [1:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:432" *)
  wire [35:0] _027_;
  (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:428" *)
  wire [8:0] _028_;
  wire _029_;
  wire _030_;
  (* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:203" *)
  wire [9:0] _031_;
  wire [9:0] _032_;
  (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *)
  wire _033_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:203" *)
  wire [9:0] _034_;
  wire [9:0] _035_;
  (* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:221" *)
  wire _036_;
  (* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)
  wire _037_;
  (* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)
  wire _038_;
  (* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)
  wire _039_;
  (* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)
  wire _040_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _041_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _042_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _043_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _044_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _045_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)
  wire _046_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)
  wire _047_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)
  wire _048_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)
  wire _049_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)
  wire _050_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)
  wire _051_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)
  wire _052_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)
  wire _053_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _054_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _055_;
  (* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)
  wire _056_;
  (* src = "tests/simple/fiedler-cooley.v:9" *)
  output borrow_out;
  reg borrow_out;
  (* src = "tests/simple/fiedler-cooley.v:9" *)
  output carry_out;
  reg carry_out;
  (* src = "tests/simple/fiedler-cooley.v:6" *)
  input clock;
  (* src = "tests/simple/fiedler-cooley.v:12" *)
  reg [8:0] count_nxt;
  (* src = "tests/simple/fiedler-cooley.v:8" *)
  output [8:0] count_out;
  (* src = "tests/simple/fiedler-cooley.v:5" *)
  input [8:0] data_in;
  (* src = "tests/simple/fiedler-cooley.v:6" *)
  input down;
  (* src = "tests/simple/fiedler-cooley.v:9" *)
  output parity_out;
  reg parity_out;
  (* src = "tests/simple/fiedler-cooley.v:6" *)
  input up;
  assign _022_ = down |(* src = "tests/simple/fiedler-cooley.v:22|tests/simple/fiedler-cooley.v:19" *)  _020_[1];
  assign _023_ = _021_[0] |(* src = "tests/simple/fiedler-cooley.v:21|tests/simple/fiedler-cooley.v:19" *)  up;
  assign _006_[0] = _027_[8] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[17];
  assign _006_[1] = _027_[26] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[35];
  assign _028_[8] = _006_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _006_[1];
  assign _007_[0] = _027_[7] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[16];
  assign _007_[1] = _027_[25] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[34];
  assign _028_[7] = _007_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _007_[1];
  assign _008_[0] = _027_[6] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[15];
  assign _008_[1] = _027_[24] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[33];
  assign _028_[6] = _008_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _008_[1];
  assign _009_[0] = _027_[5] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[14];
  assign _009_[1] = _027_[23] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[32];
  assign _028_[5] = _009_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _009_[1];
  assign _010_[0] = _027_[4] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[13];
  assign _010_[1] = _027_[22] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[31];
  assign _028_[4] = _010_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _010_[1];
  assign _011_[0] = _027_[3] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[12];
  assign _011_[1] = _027_[21] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[30];
  assign _028_[3] = _011_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _011_[1];
  assign _012_[0] = _027_[2] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[11];
  assign _012_[1] = _027_[20] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[29];
  assign _028_[2] = _012_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _012_[1];
  assign _013_[0] = _027_[1] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[10];
  assign _013_[1] = _027_[19] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[28];
  assign _028_[1] = _013_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _013_[1];
  assign _014_[0] = _027_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[9];
  assign _014_[1] = _027_[18] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _027_[27];
  assign _028_[0] = _014_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:441" *)  _014_[1];
  assign _015_[0] = _029_ |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *)  _030_;
  assign _015_[1] = _025_ |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *)  _026_;
  assign _033_ = _015_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *)  _015_[1];
  assign _016_[0] = _004_[0] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _004_[1];
  assign _016_[1] = _004_[2] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _004_[3];
  assign _016_[2] = _004_[4] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _004_[5];
  assign _016_[3] = _004_[6] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _004_[7];
  assign _017_[0] = _016_[0] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _016_[1];
  assign _017_[1] = _016_[2] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _016_[3];
  assign _018_ = _017_[0] ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _017_[1];
  assign _005_ = _018_ ^(* src = "tests/simple/fiedler-cooley.v:27" *)  _004_[8];
  assign _024_ = _021_[0] |(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19" *)  _020_[1];
  assign _019_ = down |(* src = "tests/simple/fiedler-cooley.v:20|tests/simple/fiedler-cooley.v:19" *)  up;
  assign _030_ = ~(* src = "tests/simple/fiedler-cooley.v:22|tests/simple/fiedler-cooley.v:19" *) _022_;
  assign _025_ = ~(* src = "tests/simple/fiedler-cooley.v:21|tests/simple/fiedler-cooley.v:19" *) _023_;
  assign _026_ = ~(* src = "tests/simple/fiedler-cooley.v:20|tests/simple/fiedler-cooley.v:19" *) _019_;
  assign _029_ = ~(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19" *) _024_;
  assign _004_[0] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[0] : 1'hx;
  assign _004_[1] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[1] : 1'hx;
  assign _004_[2] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[2] : 1'hx;
  assign _004_[3] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[3] : 1'hx;
  assign _004_[4] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[4] : 1'hx;
  assign _004_[5] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[5] : 1'hx;
  assign _004_[6] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[6] : 1'hx;
  assign _004_[7] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[7] : 1'hx;
  assign _004_[8] = _033_ ? (* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:445" *) _028_[8] : 1'hx;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      carry_out <= _001_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      borrow_out <= _000_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      parity_out <= _005_;
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[0] <= _004_[0];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[1] <= _004_[1];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[2] <= _004_[2];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[3] <= _004_[3];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[4] <= _004_[4];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[5] <= _004_[5];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[6] <= _004_[6];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[7] <= _004_[7];
  (* src = "tests/simple/fiedler-cooley.v:14" *)
  always @(posedge clock)
      count_nxt[8] <= _004_[8];
  assign _020_[1] = up ^(* src = "tests/simple/fiedler-cooley.v:22|tests/simple/fiedler-cooley.v:19" *)  1'h1;
  assign _021_[0] = down ^(* src = "tests/simple/fiedler-cooley.v:21|tests/simple/fiedler-cooley.v:19" *)  1'h1;
  assign _027_[27] = data_in[0] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[28] = data_in[1] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[29] = data_in[2] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[30] = data_in[3] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[31] = data_in[4] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[32] = data_in[5] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[33] = data_in[6] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[34] = data_in[7] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[35] = data_in[8] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _026_;
  assign _027_[18] = _002_[0] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[19] = _002_[1] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[20] = _002_[2] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[21] = _002_[3] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[22] = _002_[4] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[23] = _002_[5] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[24] = _002_[6] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[25] = _002_[7] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[26] = _002_[8] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _025_;
  assign _027_[9] = _002_[0] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[10] = _002_[1] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[11] = _002_[2] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[12] = _003_[3] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[13] = _003_[4] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[14] = _003_[5] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[15] = _003_[6] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[16] = _003_[7] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[17] = _003_[8] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _030_;
  assign _027_[0] = count_nxt[0] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[1] = count_nxt[1] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[2] = count_nxt[2] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[3] = count_nxt[3] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[4] = count_nxt[4] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[5] = count_nxt[5] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[6] = count_nxt[6] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[7] = count_nxt[7] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _027_[8] = count_nxt[8] &(* src = "tests/simple/fiedler-cooley.v:23|tests/simple/fiedler-cooley.v:19|<techmap.v>:434" *)  _029_;
  assign _002_[0] = count_nxt[0] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  1'h1;
  assign _002_[1] = _032_[1] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  count_nxt[0];
  assign _002_[2] = count_nxt[2] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _031_[1];
  assign _002_[3] = _035_[3] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _031_[2];
  assign _002_[4] = _035_[4] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _034_[3];
  assign _002_[5] = _035_[5] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _034_[4];
  assign _002_[6] = _035_[6] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _034_[5];
  assign _002_[7] = _035_[7] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _034_[6];
  assign _002_[8] = _035_[8] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _034_[7];
  assign _002_[9] = 1'h1 ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:263" *)  _034_[9];
  assign _032_[1] = count_nxt[1] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _035_[3] = count_nxt[3] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _035_[4] = count_nxt[4] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _035_[5] = count_nxt[5] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _035_[6] = count_nxt[6] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _035_[7] = count_nxt[7] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _035_[8] = count_nxt[8] ^(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:262" *)  1'h1;
  assign _003_[3] = count_nxt[3] ^(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:263" *)  _031_[2];
  assign _003_[4] = count_nxt[4] ^(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:263" *)  _031_[3];
  assign _003_[5] = count_nxt[5] ^(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:263" *)  _031_[4];
  assign _003_[6] = count_nxt[6] ^(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:263" *)  _031_[5];
  assign _003_[7] = count_nxt[7] ^(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:263" *)  _031_[6];
  assign _003_[8] = count_nxt[8] ^(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:263" *)  _031_[7];
  assign _036_ = _032_[1] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  count_nxt[0];
  assign _041_ = _035_[5] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  count_nxt[4];
  assign _042_ = _035_[7] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  count_nxt[6];
  assign _043_ = _046_ &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _031_[1];
  assign _044_ = _048_ &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _054_;
  assign _045_ = _049_ &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _034_[3];
  assign _046_ = _035_[3] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)  count_nxt[2];
  assign _047_ = _035_[5] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)  _035_[4];
  assign _048_ = _035_[7] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)  _035_[6];
  assign _049_ = _048_ &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:222" *)  _047_;
  assign _050_ = _047_ &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _034_[3];
  assign _031_[2] = count_nxt[2] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _031_[1];
  assign _052_ = _035_[4] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _034_[3];
  assign _053_ = _035_[6] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _034_[5];
  assign _051_ = _035_[8] &(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _034_[7];
  assign _031_[1] = count_nxt[1] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _036_;
  assign _054_ = count_nxt[5] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _041_;
  assign _055_ = count_nxt[7] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _042_;
  assign _034_[3] = count_nxt[3] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _043_;
  assign _056_ = _055_ |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _044_;
  assign _034_[7] = _056_ |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:221" *)  _045_;
  assign _034_[5] = _054_ |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _050_;
  assign _034_[9] = count_nxt[8] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _051_;
  assign _034_[4] = count_nxt[4] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _052_;
  assign _034_[6] = count_nxt[6] |(* src = "tests/simple/fiedler-cooley.v:16|<techmap.v>:260|<techmap.v>:229" *)  _053_;
  assign _031_[3] = _037_ &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:221" *)  _031_[1];
  assign _031_[7] = _040_ &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:221" *)  _031_[3];
  assign _037_ = count_nxt[3] &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)  count_nxt[2];
  assign _038_ = count_nxt[5] &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)  count_nxt[4];
  assign _039_ = count_nxt[7] &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)  count_nxt[6];
  assign _040_ = _039_ &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:222" *)  _038_;
  assign _031_[5] = _038_ &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:229" *)  _031_[3];
  assign _031_[4] = count_nxt[4] &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:229" *)  _031_[3];
  assign _031_[6] = count_nxt[6] &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:229" *)  _031_[5];
  assign _003_[9] = count_nxt[8] &(* src = "tests/simple/fiedler-cooley.v:17|<techmap.v>:260|<techmap.v>:229" *)  _031_[7];
  assign _001_ = up &(* src = "tests/simple/fiedler-cooley.v:28" *)  _003_[9];
  assign _000_ = down &(* src = "tests/simple/fiedler-cooley.v:29" *)  _002_[9];
  assign _003_[2:0] = _002_[2:0];
  assign _020_[0] = down;
  assign _021_[1] = up;
  assign { _031_[9:8], _031_[0] } = { 1'h0, _003_[9], count_nxt[0] };
  assign { _032_[9:2], _032_[0] } = { 1'h0, count_nxt[8:2], _002_[0] };
  assign { _034_[8], _034_[2:0] } = { _034_[9], _031_[2:1], count_nxt[0] };
  assign { _035_[9], _035_[2:0] } = { 1'h1, count_nxt[2], _032_[1], count_nxt[0] };
  assign count_out = count_nxt;
endmodule
